0627#5

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,5 +46,7 @@ jobs:
           python-version: "3.10"
 
       - name: Install dependencies
-        working-directory: ./be # be 디렉토리로 변경
-        run: pip install -r requirements.txt
+        working-directory: ./be
+        run: |
+          pip install --upgrade pip
+          pip install -r requirements.txt || { echo "Failed to install requirements"; exit 1; }
